import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type Item = { id:number; name:string; description:string; price:string; image?:string }
type CartItem = Item & { quantity:number }
type Order = { id:number; customer_name:string; customer_address:string; customer_phone:string; status:string; status_display:string; total_amount:string; created_at:string; items?: { id:number; menu_item_name:string; quantity:number; price:string }[] }
type Insights = { total_orders:number; total_revenue:string; active_orders:number; status_counts:Record<string,number> }
const API = import.meta.env.VITE_API_URL ?? 'http://127.0.0.1:8000/api'
const images = ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80','https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80','https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80','https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=800&q=80']
const fallback:Item[] = [{id:1,name:'Truffle mushroom pizza',description:'Mozzarella, roasted mushrooms, truffle cream & herbs',price:'18.50'},{id:2,name:'Crispy chicken burger',description:'Buttermilk chicken, slaw, pickles & house sauce',price:'14.00'},{id:3,name:'Charred broccoli bowl',description:'Grains, avocado, edamame, sesame & ginger dressing',price:'13.50'},{id:4,name:'Smoky barbecue wings',description:'Slow-roasted wings with smoked barbecue glaze',price:'12.00'}]
const money=(value:string|number)=>`$${Number(value).toFixed(2)}`

function App(){
 const [page,setPage]=useState<'home'|'menu'|'history'|'about'|'help'>('home'),[menu,setMenu]=useState<Item[]>(fallback),[cart,setCart]=useState<CartItem[]>([]),[orders,setOrders]=useState<Order[]>([]),[insights,setInsights]=useState<Insights|null>(null),[search,setSearch]=useState(''),[sort,setSort]=useState('name'),[current,setCurrent]=useState(1),[totalPages,setTotalPages]=useState(1),[checkout,setCheckout]=useState(false),[message,setMessage]=useState('')
 const total=useMemo(()=>cart.reduce((sum,item)=>sum+Number(item.price)*item.quantity,0),[cart]); const count=cart.reduce((sum,item)=>sum+item.quantity,0)
 const add=(item:Item)=>setCart(items=>items.some(x=>x.id===item.id)?items.map(x=>x.id===item.id?{...x,quantity:x.quantity+1}:x):[...items,{...item,quantity:1}])
 const change=(id:number,delta:number)=>setCart(items=>items.flatMap(x=>x.id!==id?[x]:x.quantity+delta>0?[{...x,quantity:x.quantity+delta}]:[]))
 const navigate=(next:typeof page)=>{setPage(next);setMessage('');window.scrollTo({top:0,behavior:'smooth'})}
 useEffect(()=>{if(page!=='menu'&&page!=='home')return;const timer=setTimeout(()=>fetch(`${API}/menu-items/?page=${current}&search=${encodeURIComponent(search)}&ordering=${sort}`).then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(Array.isArray(data)) {setMenu(data);setTotalPages(1)} else {setMenu(data.results);setTotalPages(Math.max(1,Math.ceil(data.count/8)))}}).catch(()=>setMenu(fallback)),250);return()=>clearTimeout(timer)},[page,current,search,sort])
 const refreshHistory=async()=>{try{const [orderResponse,insightsResponse]=await Promise.all([fetch(`${API}/orders/`),fetch(`${API}/orders/insights/`)]);const data=await orderResponse.json();setOrders(Array.isArray(data)?data:data.results||[]);if(insightsResponse.ok)setInsights(await insightsResponse.json())}catch{setMessage('Start the backend to see saved orders.')}}
 useEffect(()=>{if(page==='history')void refreshHistory()},[page])
 useEffect(()=>{setCurrent(1)},[search,sort])
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);try{const r=await fetch(`${API}/orders/`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer_name:form.get('name'),customer_address:form.get('address'),customer_phone:form.get('phone'),items:cart.map(x=>({menu_item_id:x.id,quantity:x.quantity}))})});if(!r.ok)throw Error();const order=await r.json() as Order;setCart([]);setCheckout(false);setOrders(items=>[order,...items]);navigate('history');setMessage(`Order #${order.id} is received and being tracked.`)}catch{setMessage('Could not place the order. Please make sure the Django server is running.')}}
 const Header=()=> <header><button className="brand" onClick={()=>navigate('home')}>plated<span>•</span></button><nav>{(['home','menu','history','about','help'] as const).map(x=><button className={page===x?'nav-active':''} key={x} onClick={()=>navigate(x)}>{x==='home'?'Home':x[0].toUpperCase()+x.slice(1)}</button>)}</nav><button className="cart-button" onClick={()=>count&&setCheckout(true)}>Bag <b>{count}</b></button></header>
 const Cards=()=> <div className="menu-grid">{menu.map((item,index)=><article className="food-card" key={item.id}><img src={item.image||images[index%images.length]} alt={item.name}/><div className="card-details"><div className="item-row"><h3>{item.name}</h3><strong>{money(item.price)}</strong></div><p>{item.description}</p><button className="add-button" onClick={()=>add(item)}>Add to bag <span>+</span></button></div></article>)}</div>
 const Home=()=> <><section className="hero"><div><p className="eyebrow">GOOD FOOD, DELIVERED</p><h1>A little joy,<br/><em>plated.</em></h1><p className="hero-copy">Your neighborhood favorites, thoughtfully picked and sent straight to your door.</p><button className="primary-button" onClick={()=>navigate('menu')}>Browse the menu <span>↓</span></button></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1100&q=85" alt="Colourful food spread"/><div className="hero-note"><b>30–45 min</b><span>at your doorstep</span></div></div></section><section className="menu-section"><div className="section-heading"><div><p className="eyebrow">TODAY’S PICKS</p><h2>Made for your mood.</h2></div><button className="text-button" onClick={()=>navigate('menu')}>View full menu →</button></div><Cards/></section></>
 const Menu=()=> <section className="page-section"><p className="eyebrow">ALL DAY, EVERY DAY</p><h1>Find your next<br/><em>favourite.</em></h1><div className="menu-tools"><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pizza, bowl, burger…"/></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name A–Z</option><option value="-name">Name Z–A</option><option value="price">Price: low to high</option><option value="-price">Price: high to low</option></select></label></div><Cards/><div className="pagination"><button disabled={current===1} onClick={()=>setCurrent(x=>x-1)}>← Previous</button>{Array.from({length:totalPages},(_,i)=><button className={current===i+1?'selected':''} key={i} onClick={()=>setCurrent(i+1)}>{i+1}</button>)}<button disabled={current===totalPages} onClick={()=>setCurrent(x=>x+1)}>Next →</button></div></section>
 const History=()=> <section className="page-section history"><div className="history-heading"><div><p className="eyebrow">YOUR ORDERS</p><h1>Good meals,<br/><em>good memories.</em></h1></div><button className="secondary-button" onClick={()=>void refreshHistory()}>Refresh live status ↻</button></div>{insights&&<div className="insight-grid"><article><span>All orders</span><b>{insights.total_orders}</b></article><article><span>In progress</span><b>{insights.active_orders}</b></article><article><span>Order value</span><b>{money(insights.total_revenue)}</b></article><article><span>Delivered</span><b>{insights.status_counts.delivered||0}</b></article></div>}{orders.length?<div className="order-list">{orders.map(order=><article className="order-card" key={order.id}><div><p className="eyebrow">ORDER #{order.id} · {new Date(order.created_at).toLocaleDateString()}</p><h3>{order.items?.map(x=>`${x.quantity}× ${x.menu_item_name}`).join(', ')||'Your delicious order'}</h3><p className="address">Delivering to {order.customer_address}</p></div><div className="order-meta"><span className={`status ${order.status}`}>{order.status_display}</span><strong>{money(order.total_amount)}</strong></div></article>)}</div>:<div className="empty"><h2>Your order history is empty.</h2><p>When you place an order, its live status will appear right here.</p><button className="primary-button" onClick={()=>navigate('menu')}>Explore menu →</button></div>}</section>
 const Static=({kind}:{kind:'about'|'help'})=> <section className="page-section info"><p className="eyebrow">{kind==='about'?'OUR LITTLE KITCHEN':'WE’RE HERE TO HELP'}</p><h1>{kind==='about'?<>Food worth<br/><em>waiting for.</em></>:<>Questions?<br/><em>We’ve got you.</em></>}</h1>{kind==='about'?<><p>Plated brings the best dishes from local kitchens to your doorstep. We obsess over the small details, so every meal arrives feeling a little special.</p><div className="info-grid"><article><h3>Thoughtfully picked</h3><p>A focused menu of food we’d happily eat ourselves.</p></article><article><h3>Made nearby</h3><p>Prepared fresh by local cooks and restaurants.</p></article><article><h3>Easy delivery</h3><p>Clear updates from checkout to your front door.</p></article></div></>:<div className="faq"><article><h3>How do I track my order?</h3><p>Open Order history after placing your order. Statuses progress automatically in this demo.</p></article><article><h3>Can I change my delivery address?</h3><p>Please contact us before the order reaches “Out for Delivery”.</p></article><article><h3>Need more help?</h3><p>Email hello@plated.example and our friendly team will be in touch.</p></article></div>}</section>
 return <main><Header/>{message&&<div className="toast">{message}<button onClick={()=>setMessage('')}>×</button></div>}{page==='home'?<Home/>:page==='menu'?<Menu/>:page==='history'?<History/>:<Static kind={page}/>}<section className="cart-strip"><div><span className="cart-dot">{count}</span><b>{count?`${count} item${count===1?'':'s'} in your bag`:'Your bag is waiting'}</b><small>{count?money(total):'Add something delicious to get started'}</small></div><button className="primary-button" disabled={!count} onClick={()=>setCheckout(true)}>Checkout →</button></section>{checkout&&<div className="modal-backdrop" onMouseDown={()=>setCheckout(false)}><form className="checkout-modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button className="close" type="button" onClick={()=>setCheckout(false)}>×</button><p className="eyebrow">YOUR BAG</p><h2>One last look.</h2><div className="checkout-items">{cart.map(item=><div className="checkout-item" key={item.id}><span>{item.name}</span><div className="quantity"><button type="button" onClick={()=>change(item.id,-1)}>−</button><b>{item.quantity}</b><button type="button" onClick={()=>change(item.id,1)}>+</button></div><strong>{money(Number(item.price)*item.quantity)}</strong></div>)}</div><p className="eyebrow delivery-label">DELIVERY DETAILS</p><label>Your name<input name="name" required placeholder="Alex Morgan"/></label><label>Delivery address<textarea name="address" required placeholder="12 Market Street, Apartment 4B"/></label><label>Phone number<input name="phone" required type="tel" placeholder="(555) 123-4567"/></label><div className="checkout-total"><span>Your total</span><strong>{money(total)}</strong></div><button className="primary-button full">Place order →</button></form></div>}</main>
}
export default App
